### ISSUE TITLE
Ending Labs with minikube delete

### ISSUE THREAD

**Issue by lstif** [ManicodeSecurity/Defending-DevOps#12]
Most labs start with 
`export MINIKUBE_HOME=~/Desktop/lab-tools/.kube`
`minikube delete`
I think it would make more sense if the labs ended with this step instead of it being at the beginning of the next lab

**Comment by CMeza99** [comment]
Pull requests welcomed.

**Comment by jmbmxer** [comment]
Minikube is GONE.
